### ISSUE TITLE
Several request at a time

### ISSUE THREAD

**Issue by bsoun** [TwoUnderscorez/vscode-websearch#3]
It would be awesome if we can :  
- define specific urls, ie for google, add some param like site:... ext:.. 
- launch request on several browser tabs.
Here is a sample I made in the past for sublime text [bang-search](https://github.com/bsoun/bang-search).

**Comment by TwoUnderscorez** [comment]
- you can charge the tld in the config (.co.uk, .ca, etc...) Is that what you mean?
- What do you mean by "launch request on several browser tabs"
